services:
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    restart: always

# docker-compose up -d
# docker-compose down
# docker-compose restart nginx
