# Runs the server in standalone mode.
listen=YES

# Disables anonymous FTP access for better security.
anonymous_enable=NO

# Enables local user accounts for login.
local_enable=YES

# Allows file uploads and modifications by authenticated users.
write_enable=YES

# Specifies the default FTP port
listen_port=21

# Sets the home directory for local users to /ftp-server/files.
chroot_local_user=YES
local_root=/ftp-server/files

# Limits the range of ports used for passive mode data connections.
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
pasv_address=192.168.42.1
