services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "4243:4242"
      # Maps port 4243 on the host to port 4242 in the nginx-container.
      # This allows SSH access from the host on port 4243.
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sshd_config:/etc/ssh/sshd_config:ro
      - ./html:/usr/share/nginx/html:ro
      # Mounts the file/directory into the container with read-only permissions.
    depends_on:
      - tor
      # Ensures the tor service starts before the nginx service.

  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    container_name: tor-container
    volumes:
      - ./tor/torrc:/etc/tor/torrc:ro
